UPDATE games SET rating_metacritic = 67, rating_rawg = 3.72 WHERE id = 1;
UPDATE games SET rating_metacritic = 75, rating_rawg = 4.41 WHERE id = 2;
UPDATE games SET rating_metacritic = 73, rating_rawg = 2.91 WHERE id = 3;
UPDATE games SET rating_metacritic = 55, rating_rawg = 3.52 WHERE id = 4;
UPDATE games SET rating_rawg = 3.15 WHERE id = 8;
UPDATE games SET rating_metacritic = 83, rating_rawg = 3.96 WHERE id = 9;
UPDATE games SET rating_metacritic = 91, rating_rawg = 4.16 WHERE id = 5;
UPDATE games SET rating_metacritic = 86, rating_rawg = 4.21 WHERE id = 6;
UPDATE games SET rating_metacritic = 92, rating_rawg = 4.39 WHERE id = 7;
UPDATE games SET rating_rawg = 4.48 WHERE id = 10;
UPDATE games SET rating_metacritic = 81, rating_rawg = 4.12 WHERE id = 11;
UPDATE games SET rating_metacritic = 87, rating_rawg = 4.37 WHERE id = 57;
UPDATE games SET rating_metacritic = 76, rating_rawg = 3.58 WHERE id = 12;
UPDATE games SET rating_metacritic = 76, rating_rawg = 3.42 WHERE id = 13;
UPDATE games SET rating_metacritic = 90, rating_rawg = 3.74 WHERE id = 14;
UPDATE games SET rating_metacritic = 85, rating_rawg = 4.02 WHERE id = 15;
UPDATE games SET rating_rawg = 3.41 WHERE id = 16;
UPDATE games SET rating_rawg = 3.71 WHERE id = 17;
UPDATE games SET rating_metacritic = 79, rating_rawg = 4.12 WHERE id = 18;
UPDATE games SET rating_metacritic = 61, rating_rawg = 3.76 WHERE id = 19;
UPDATE games SET rating_rawg = 3.58 WHERE id = 20;
UPDATE games SET rating_metacritic = 90, rating_rawg = 4.28 WHERE id = 21;
UPDATE games SET rating_metacritic = 79, rating_rawg = 4.14 WHERE id = 22;
UPDATE games SET rating_metacritic = 77, rating_rawg = 3.46 WHERE id = 23;
UPDATE games SET rating_metacritic = 88, rating_rawg = 4.12 WHERE id = 24;
UPDATE games SET rating_metacritic = 88, rating_rawg = 4.12 WHERE id = 25;
UPDATE games SET rating_rawg = 3.42 WHERE id = 26;
UPDATE games SET rating_metacritic = 82, rating_rawg = 4.38 WHERE id = 27;
UPDATE games SET rating_rawg = 4.25 WHERE id = 28;
UPDATE games SET rating_rawg = 3.92 WHERE id = 29;
UPDATE games SET rating_metacritic = 87, rating_rawg = 4.38 WHERE id = 30;
UPDATE games SET rating_rawg = 3.98 WHERE id = 33;
UPDATE games SET rating_rawg = 3.58 WHERE id = 34;
UPDATE games SET rating_metacritic = 78, rating_rawg = 3.65 WHERE id = 35;
UPDATE games SET rating_metacritic = 88, rating_rawg = 4.14 WHERE id = 36;
UPDATE games SET rating_metacritic = 81, rating_rawg = 3.18 WHERE id = 37;
UPDATE games SET rating_metacritic = 78, rating_rawg = 4.24 WHERE id = 38;
UPDATE games SET rating_metacritic = 79, rating_rawg = 3.94 WHERE id = 39;
UPDATE games SET rating_metacritic = 83, rating_rawg = 4.44 WHERE id = 40;
UPDATE games SET rating_rawg = 2.75 WHERE id = 42;
UPDATE games SET rating_rawg = 3.56 WHERE id = 43;
UPDATE games SET rating_rawg = 4.03 WHERE id = 44;
UPDATE games SET rating_metacritic = 90, rating_rawg = 4.49 WHERE id = 45;
UPDATE games SET rating_rawg = 4.5 WHERE id = 46;
UPDATE games SET rating_metacritic = 91, rating_rawg = 4.5 WHERE id = 48;
UPDATE games SET rating_metacritic = 79, rating_rawg = 3.61 WHERE id = 49;
UPDATE games SET rating_rawg = 3.93 WHERE id = 50;
UPDATE games SET rating_rawg = 1.95 WHERE id = 51;
UPDATE games SET rating_metacritic = 69, rating_rawg = 3.62 WHERE id = 52;
UPDATE games SET rating_metacritic = 72, rating_rawg = 3.41 WHERE id = 53;
UPDATE games SET rating_rawg = 3.88 WHERE id = 54;
UPDATE games SET rating_metacritic = 90, rating_rawg = 4.02 WHERE id = 56;
UPDATE games SET rating_rawg = 4.12 WHERE id = 58;
UPDATE games SET rating_rawg = 2.65 WHERE id = 31;
UPDATE games SET rating_rawg = 2.65 WHERE id = 32;