UPDATE games SET rating_metacritic = 67 WHERE title = 'AO Tennis 2';
UPDATE games SET rating_metacritic = 75 WHERE title = 'Batman: Return to Arkham - Arkham Asylum';
UPDATE games SET rating_metacritic = 73 WHERE title = 'Black Desert';
UPDATE games SET rating_metacritic = 55 WHERE title = 'Bright Memory';
UPDATE games SET rating_metacritic = 83 WHERE title = 'Call of Duty: World at War';
UPDATE games SET rating_metacritic = 91 WHERE title = 'Call of Duty® (2003)';
UPDATE games SET rating_metacritic = 86 WHERE title = 'Call of Duty® 2';
UPDATE games SET rating_metacritic = 92 WHERE title = 'Call of Duty® 4: Modern Warfare® (2007)';
UPDATE games SET rating_metacritic = 81 WHERE title = 'Crash Bandicoot N. Sane Trilogy | C1';
UPDATE games SET rating_metacritic = 87 WHERE title = 'Cuphead';
UPDATE games SET rating_metacritic = 76 WHERE title = 'Darksiders Genesis';
UPDATE games SET rating_metacritic = 76 WHERE title = 'Descenders';
UPDATE games SET rating_metacritic = 90 WHERE title = 'Diablo IV';
UPDATE games SET rating_metacritic = 85 WHERE title = 'DmC: Devil May Cry';
UPDATE games SET rating_metacritic = 79 WHERE title = 'Euro Truck Simulator 2';
UPDATE games SET rating_metacritic = 61 WHERE title = 'Evoland';
UPDATE games SET rating_metacritic = 90 WHERE title = 'Final Fantasy VIII';
UPDATE games SET rating_metacritic = 79 WHERE title = 'Final Fantasy VIII Remastered';
UPDATE games SET rating_metacritic = 77 WHERE title = 'Final Fantasy XIII';
UPDATE games SET rating_metacritic = 88 WHERE title = 'Final Fantasy XVI';
UPDATE games SET rating_metacritic = 88 WHERE title = 'Final Fantasy XVI DEMO';
UPDATE games SET rating_metacritic = 82 WHERE title = 'Guitar Hero III: Legends of Rock';
UPDATE games SET rating_metacritic = 87 WHERE title = 'Inside';
UPDATE games SET rating_metacritic = 78 WHERE title = 'League Of Legends';
UPDATE games SET rating_metacritic = 88 WHERE title = 'Limbo';
UPDATE games SET rating_metacritic = 81 WHERE title = 'Lost Ark';
UPDATE games SET rating_metacritic = 78 WHERE title = 'Mafia: Definitive Edition';
UPDATE games SET rating_metacritic = 79 WHERE title = 'Metro 2033';
UPDATE games SET rating_metacritic = 83 WHERE title = 'Minecraft: Java Edition';
UPDATE games SET rating_metacritic = 90 WHERE title = 'Portal';
UPDATE games SET rating_metacritic = 91 WHERE title = 'Resident Evil 2';
UPDATE games SET rating_metacritic = 80 WHERE title = 'Resident Evil 3';
UPDATE games SET rating_metacritic = 79 WHERE title = 'Scarlet Nexus';
UPDATE games SET rating_metacritic = 69 WHERE title = 'The Gunk';
UPDATE games SET rating_metacritic = 72 WHERE title = 'The Incredible Adventures of Van Helsing';
UPDATE games SET rating_metacritic = 97 WHERE title = 'The Legend of Zelda: Breath of the Wild';
UPDATE games SET rating_metacritic = 93 WHERE title = 'Uncharted 4: A Thief''s End - Remastered';
UPDATE games SET rating_metacritic = 90 WHERE title = 'World of Goo';